apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openmpi-test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openmpi-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openmpi-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openmpi-test
subjects:
- kind: ServiceAccount
  name: openmpi-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openmpi-scripts
data:
  kubexec: |-
    #!/usr/bin/env bash
    REMOTE_HOST=$1
    shift
    kubectl exec ${REMOTE_HOST} -- bash -c "$*"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openmpi-worker
spec:
  podManagementPolicy: Parallel
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: openmpi-worker
  serviceName: openmpi-worker
  replicas: 4
  template:
    metadata:
      labels:
        app: openmpi-worker
    spec:
      serviceAccountName: openmpi-test
      containers:
      - name: openmpi-worker
        image: rongou/openmpi-worker
        command: ["sleep"]
        args: ["infinity"]
        volumeMounts:
        - name: openmpi-scripts
          mountPath: /opt/mpi
      volumes:
      - name: openmpi-scripts
        configMap:
          name: openmpi-scripts
          defaultMode: 0700
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openmpi-hostfile
data:
  hostfile: |-
    openmpi-worker-0 slots=4 max_slots=4
    openmpi-worker-1 slots=4 max_slots=4
    openmpi-worker-2 slots=4 max_slots=4
    openmpi-worker-3 slots=4 max_slots=4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: openmpi-launcher
spec:
  template:
    spec:
      serviceAccountName: openmpi-test
      containers:
      - name: openmpi-launcher
        image: rongou/openmpi-launcher
        command: ["mpirun"]
        args: [
          "-allow-run-as-root",
          "-bind-to", "none",
          "-map-by", "slot",
          "-hostfile",
          "/etc/mpi/hostfile",
          "hostname"
        ]
        env:
        - name: OMPI_MCA_plm_rsh_agent
          value: /opt/mpi/kubexec
        volumeMounts:
        - name: openmpi-hostfile
          mountPath: /etc/mpi
        - name: openmpi-scripts
          mountPath: /opt/mpi
      volumes:
      - name: openmpi-hostfile
        configMap:
          name: openmpi-hostfile
          defaultMode: 0400
      - name: openmpi-scripts
        configMap:
          name: openmpi-scripts
          defaultMode: 0500
      restartPolicy: Never
