apiVersion: v1
kind: ConfigMap
metadata:
  name: openmpi-scripts
data:
  kubexec.sh: |-
    #!/bin/sh
    REMOTE_HOST=$1
    shift
    kubectl exec ${REMOTE_HOST} -- /bin/sh -c "$*"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openmpi-worker
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: openmpi-worker
  serviceName: openmpi-worker
  replicas: 4
  template:
    metadata:
      labels:
        app: openmpi-worker
    spec:
      containers:
      - name: openmpi-worker
        image: rongou/openmpi-worker
        command: ["sleep"]
        args: ["365d"]
        volumeMounts:
        - name: openmpi-scripts
          mountPath: /opt/mpi
      volumes:
      - name: openmpi-scripts
        configMap:
          name: openmpi-scripts
          defaultMode: 0500
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openmpi-test
rules:
- apiGroups: [""]
  resources: ["pods"]
  resourceNames: [
    "openmpi-worker-0",
    "openmpi-worker-1",
    "openmpi-worker-2",
    "openmpi-worker-3"
  ]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  resourceNames: [
    "openmpi-worker-0",
    "openmpi-worker-1",
    "openmpi-worker-2",
    "openmpi-worker-3"
  ]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openmpi-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openmpi-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openmpi-test
subjects:
- kind: ServiceAccount
  name: openmpi-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openmpi-hostfile
data:
  hostfile: |-
    openmpi-worker-0 slots=4 max_slots=4
    openmpi-worker-1 slots=4 max_slots=4
    openmpi-worker-2 slots=4 max_slots=4
    openmpi-worker-3 slots=4 max_slots=4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: openmpi-launcher
spec:
  template:
    spec:
      serviceAccountName: openmpi-test
      securityContext:
        runAsUser: 1009
        fsGroup: 2003
      containers:
      - name: openmpi-launcher
        image: rongou/openmpi-launcher
        command: ["mpirun"]
        args: [
          "--mca", "plm_rsh_agent", "/opt/mpi/kubexec.sh",
          "--bind-to", "none",
          "--map-by", "slot",
          "--hostfile", "/etc/mpi/hostfile",
          "hostname"
        ]
        volumeMounts:
        - name: openmpi-hostfile
          mountPath: /etc/mpi
        - name: openmpi-scripts
          mountPath: /opt/mpi
      volumes:
      - name: openmpi-hostfile
        configMap:
          name: openmpi-hostfile
          defaultMode: 0440
      - name: openmpi-scripts
        configMap:
          name: openmpi-scripts
          defaultMode: 0550
      restartPolicy: Never
