apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmpi-worker
  labels:
    app: openmpi-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openmpi-worker
  template:
    metadata:
      labels:
        app: openmpi-worker
    spec:
      containers:
      - name: openmpi
        image: rongou/openmpi
        command: ["/bin/sh"]
        args: ["-c", "ssh-keygen -A && /usr/sbin/sshd -o StrictModes=no -D -e"]
        volumeMounts:
        - name: ssh-keys
          mountPath: "/root/.ssh"
      volumes:
      - name: ssh-keys
        secret:
          secretName: ssh-keys
          defaultMode: 256
          items:
          - key: id_ed25519.pub
            path: authorized_keys
